### PR TITLE
feat: update stdlib function `at` of list is deprecated

### PR DESCRIPTION
**Pull request by mrgleam**

### CODE REVIEW

**Comment by mrdimosthenis** [comment]
Thank you @mrgleam for the PR 🙂

**Comment by mrgleam** [comment]
> Thank you @mrgleam for the PR 🙂

Glad I could be of assistance.

Can you release new versions please?

**Comment by mrdimosthenis** [comment]
> > Thank you @mrgleam for the PR 🙂
> 
> Glad I could be of assistance.
> 
> Can you release new versions please?

@mrgleam the new version [0.1.1](https://hex.pm/packages/minigen/0.1.1) has been released

**Comment by mrgleam** [comment]
> > > Thank you @mrgleam for the PR 🙂
> > 
> > 
> > Glad I could be of assistance.
> > Can you release new versions please?
> 
> @mrgleam the new version [0.1.1](https://hex.pm/packages/minigen/0.1.1) has been released

Thank you very much.

**Pull request merged**
